name: example-cron
'on':
  schedule:
    - cron: 20 3 * * *
  workflow_dispatch: null
jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
